### ISSUE TITLE
navbar links

### ISSUE THREAD

**Issue by rukundoeric** [sinansevgi/NextWebClone#3]
Good work on this project, Your page looks like the original page, and your code is written with one space indentation to manage readability of your code, but in the navbar, you forgot to wrap your links in `<a href=""></a>` tag.

**Comment by sinansevgi** [comment]
Please read carefully. Only the master of the meeting should create an issue. 
[Microverse Zendesk Entry About Peer-to-Peer Code Reviews](https://microverse.zendesk.com/hc/en-us/articles/360042295413-How-do-we-conduct-a-Peer-to-peer-code-review-session-)
