### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ghost** [sinansevgi/NextWebClone#5]
Great job. I really don't see any issues, for now, maybe just one about the mobile-first approach, as it was the project's requirement.
Otherwise brilliant. Hard work is done

**Comment by sinansevgi** [comment]
Please read carefully. Only the master of the meeting should create an issue. 
[Microverse Zendesk Entry About Peer-to-Peer Code Reviews](https://microverse.zendesk.com/hc/en-us/articles/360042295413-How-do-we-conduct-a-Peer-to-peer-code-review-session-)

**Comment by ghost** [comment]
Thanks for a reminder
